apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: kivindu744/my-app:4c3a73dc6c7dd1879a0b380cb8aaad601626f4a2
        ports:
        - containerPort: 3000
