apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: kivindu744/my-app:c64ca8d5ef9a8517ed68f6af3da3a5d3457d16e4
        ports:
        - containerPort: 3000
