apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: kivindu744/my-app:b9ddc4f37da84fec94dd4739aaaf5356f68c08fa
        ports:
        - containerPort: 3000
